GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Produto",
    "price": 100
}

###
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "name": "Produto Alterado"
}

###
DELETE http://localhost:3000/products/2